services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '54322:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: campus360
    volumes:
      - campus360_pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d campus360']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  campus360_pg:
